model:
  logdir: home/jk/Joint-Diffusion-in-Latent-Space/
  base_learning_rate: 1.0e-04
  weight_decay: 0.0001
  model_type: joint_latent_diffusion_multilabel
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: 0
    image_size: 32
    channels: 4
    monitor: val/auroc_ema
    #weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    # 15 classes, log
    # weights: [1.065099588, 1.779603253, 1.551821122, 1.873975748, 1.043947633, 1.859830453, 1.916502338, 2.869185932, 0.818237579, 1.396153514, 1.326128693, 1.658934256, 2.072830496, 1.586778408, 0.02886104]
    #14 classes, log
    #weights: [0.741790821, 1.485960814, 1.253424332, 1.581670469, 0.718735907, 1.567343026, 1.624709854, 2.581797199, 0.464784148, 1.092677857, 1.019675586, 1.363090079, 1.782541339, 1.289286516]
    # 14 classes sqrt
    weights: [2.349067037, 5.533251459, 4.233622847, 6.177819776, 2.287536085, 6.076752008, 6.491647465, 19.53883204, 1.707623308, 3.518349097, 3.234728186, 4.80335892, 7.785216056, 4.412078777]

    classification_key: 1
    classification_loss_weight: 0.001
    augmentations: False
    classification_start: 3000
    classifier_in_features: 50
    classifier_hidden: 2048 #now calculated in code
    num_classes: 14 # we can have 15 with last column, or 14 without
    dropout: 0.3

    unet_config:
      target: models.AdjustedUNet
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4,2,1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4]
        #num_head_channels: 32
        pool_size: 10000
        pool_type: avg
        num_head_channels: 32

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
        ckpt_path: "logs/compvis32x32x4_all_randomresizedcrop_Autoencoder_2024-01-17T13-15-27/checkpoints/epoch=000025.ckpt"
        #ckpt_path: "/net/pr2/projects/plgrid/plggsano/plgjoaxkal_storage/Joint-Diffusion-in-Latent-Space/logs/compvis32x32x4_all_randomresizedcrop_Autoencoder_2024-01-17T13-15-27/checkpoints/epoch=000025.ckpt"
        #ckpt_path: "logs/compvis32x32x4_nihAll_maxstron_aug_Autoencoder_2024-01-30T22-29-08/checkpoints/epoch=000028.ckpt"
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_unconditional__


dataloaders:
  name: chest_xray_nih
  train_batches: [ 64 ] #96 for RAM40, 196 for RAM80
  val_batch: 128
  num_workers: 6
  num_labeled: null
  pin_memory: True
  persistent_workers: True
  training_platform: local_sano
  #training_platform: plgrid



lightning:
  trainer:
    benchmark: True
    checkpoint_callback: True
    max_steps: 100000
    gpus: -1
    accelerator: ddp
    # accumulate_grad_batches: 2
      
  callbacks:
    img_logger:
      batch_frequency: 5000
      max_images: 10
      clamp: True
      increase_log_steps: False
      log_images_kwargs: {
          "N": 10,
          "inpaint": False,
          "sample_classes": [0,1,2,3,4,5,6,7,8,9,10,11,12,13]
      }
