model:
  base_learning_rate: 0.0003
  model_type: diffmatch_wideresnet
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    log_every_t: 200
    timesteps: 1000
    first_stage_key: 0
    image_size: 32
    channels: 3
    monitor: val/loss_ema
    classification_loss_weight: 0.001
    batch_size: 64

    unet_config:
      target: models.Wide_ResNet_UNet
      params:
        num_classes: 10
        repr_channels: [
          32, 32, 32, 32,
          64, 64, 64, 64,
          128, 128, 128, 128, 128
        ]
        unet_layer_idx: [ 0, 1, 2, 3 ]
        decoder_channels_mult: [ 1, 2, 3 ]
        ds: 9
        out_channels: 3
        model_channels: 128
        attention_resolutions: [ 32, 16, 8 ]
        num_res_blocks: 3
        num_heads: 4
        dropout: 0.3


dataloaders:
  name: svhn_randaugment
  train_batches: [ 64 ]
  val_batch: 256
  num_workers: 16
  num_labeled: 1000


lightning:
  trainer:
    benchmark: True
    checkpoint_callback: True
    max_steps: 1000000
    # accumulate_grad_batches: 2

  callbacks:
    fid_logger:
      batch_frequency: 100000
      samples_amount: 10000
      metrics_batch_size: 512
      real_dl_batch_size: 448
      latent: False
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]

    img_logger:
      batch_frequency: 10000
      max_images: 10
      clamp: True
      increase_log_steps: False
      log_images_kwargs: {
          "N": 10,
          "inpaint": False,
      }
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]