#!/bin/bash

python -m torch.distributed.run --nproc_per_node=4 train_joint_diffusion_cl.py -p configs/standard_diffusion/continual_learning/joint_diffusion_pooling/imagenet100/imagenet100_sigle_task.yaml -t 0 --tags 5_tasks -d CL_IMAGENET100_TASK1_SEED42 -s 42
python -m torch.distributed.run --nproc_per_node=4 train_joint_diffusion_cl.py -p configs/standard_diffusion/continual_learning/joint_diffusion_pooling/imagenet100/imagenet100_next_sigle_task.yaml -t 1 --tags 5_tasks -c logs/CL_IMAGENET100_TASK1_SEED42/checkpoints/last.ckpt -d CL_IMAGENET100_TASK2_SEED42 -s 42
python -m torch.distributed.run --nproc_per_node=4 train_joint_diffusion_cl.py -p configs/standard_diffusion/continual_learning/joint_diffusion_pooling/imagenet100/imagenet100_kl_t2.yaml -t 1 -l 0 -o logs/CL_IMAGENET100_TASK1_SEED42/checkpoints/last.ckpt -n logs/CL_IMAGENET100_TASK2_SEED42/checkpoints/last.ckpt -c logs/CL_IMAGENET100_TASK1_SEED42/checkpoints/last.ckpt -d CL_IMAGENET100_TASK1-2_SEED42 -s 42
python -m torch.distributed.run --nproc_per_node=4 train_joint_diffusion_cl.py -p configs/standard_diffusion/continual_learning/joint_diffusion_pooling/imagenet100/imagenet100_next_sigle_task.yaml -t 2 --tags 5_tasks -c logs/CL_IMAGENET100_TASK1-2_SEED42/checkpoints/last.ckpt -d CL_IMAGENET100_TASK3_SEED42 -s 42
python -m torch.distributed.run --nproc_per_node=4 train_joint_diffusion_cl.py -p configs/standard_diffusion/continual_learning/joint_diffusion_pooling/imagenet100/imagenet100_kl_t3.yaml -t 2 -l 0 1 -o logs/CL_IMAGENET100_TASK1-2_SEED42/checkpoints/last.ckpt -n logs/CL_IMAGENET100_TASK3_SEED42/checkpoints/last.ckpt -c logs/CL_IMAGENET100_TASK1-2_SEED42/checkpoints/last.ckpt -d CL_IMAGENET100_TASK1-3_SEED42 -s 42
python -m torch.distributed.run --nproc_per_node=4 train_joint_diffusion_cl.py -p configs/standard_diffusion/continual_learning/joint_diffusion_pooling/imagenet100/imagenet100_next_sigle_task.yaml -t 3 --tags 5_tasks -c logs/CL_IMAGENET100_TASK1-3_SEED42/checkpoints/last.ckpt -d CL_IMAGENET100_TASK4_SEED42 -s 42
python -m torch.distributed.run --nproc_per_node=4 train_joint_diffusion_cl.py -p configs/standard_diffusion/continual_learning/joint_diffusion_pooling/imagenet100/imagenet100_kl_t4.yaml -t 3 -l 0 1 2 -o logs/CL_IMAGENET100_TASK1-3_SEED42/checkpoints/last.ckpt -n logs/CL_IMAGENET100_TASK4_SEED42/checkpoints/last.ckpt -c logs/CL_IMAGENET100_TASK1-3_SEED42/checkpoints/last.ckpt -d CL_IMAGENET100_TASK1-4_SEED42 -s 42
python -m torch.distributed.run --nproc_per_node=4 train_joint_diffusion_cl.py -p configs/standard_diffusion/continual_learning/joint_diffusion_pooling/imagenet100/imagenet100_next_sigle_task.yaml -t 4 --tags 5_tasks -c logs/CL_IMAGENET100_TASK1-4_SEED42/checkpoints/last.ckpt -d CL_IMAGENET100_TASK5_SEED42 -s 42
python -m torch.distributed.run --nproc_per_node=4 train_joint_diffusion_cl.py -p configs/standard_diffusion/continual_learning/joint_diffusion_pooling/imagenet100/imagenet100_kl_t5.yaml -t 4 -l 0 1 2 3 -o logs/CL_IMAGENET100_TASK1-4_SEED42/checkpoints/last.ckpt -n logs/CL_IMAGENET100_TASK5_SEED42/checkpoints/last.ckpt -c logs/CL_IMAGENET100_TASK1-4_SEED42/checkpoints/last.ckpt -d CL_IMAGENET100_TASK1-5_SEED42 -s 42