model:
  logdir: .
  base_learning_rate: 0.0001
  weight_decay: 0.0001
  model_type: multilabel_classifier_on_ldm

  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: 0
    image_size: 32
    channels: 4
    monitor: val/auroc_ema
    weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    # weights: [3.67, 3.78, 3.86, 6.2, 3.0, 2.0, 2.91, 4.18, 2.16, 3.14, 3.47, 2.82, 4.35, 1.53, 0.5]
    ft_enc: True


    classification_key: 1
    classification_loss_weight: 1
    augmentations: False

    classifier_in_features: 24064 #18048
    classifier_hidden: 2048 #now calculated in code
    num_classes: 15
    dropout: 0.3

    unet_config:
      target: models.AdjustedUNet
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 256
        attention_resolutions: [ 1,2,4 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4]
        num_head_channels: 32
        pool_size: 8 #10000

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
        ckpt_path: "/home/jk/Joint-Diffusion-in-Latent-Space/logs/compvis32x32x4_all_randomresizedcrop_Autoencoder_2024-01-17T13-15-27/checkpoints/epoch=000025.ckpt"
        #ckpt_path: "/net/pr2/projects/plgrid/plggsano/plgjoaxkal_storage/Joint-Diffusion-in-Latent-Space/logs/compvis32x32x4_nihAll_maxstron_aug_Autoencoder_2024-01-30T22-29-08/checkpoints/epoch=000028.ckpt"
        #ckpt_path: "/net/pr2/projects/plgrid/plggsano/plgjoaxkal_storage/Joint-Diffusion-in-Latent-Space/logs/compvis32x32x4_all_randomresizedcrop_Autoencoder_2024-01-17T13-15-27/checkpoints/epoch=000025.ckpt"
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_unconditional__


dataloaders:
  name: chest_xray_nih
  train_batches: [ 1 ]
  val_batch: 1
  min_augmentation_ratio: 8
  auto_augment: False
  num_workers: 12
  num_labeled: null
  pin_memory: True
  persistent_workers: True
  training_platform: local_sano
  #training_platform: plgrid

lightning:
  trainer:
    benchmark: True
    checkpoint_callback: True
    max_steps: 100000
    gpus: -1
    accelerator: ddp
    # accumulate_grad_batches: 