model:
  base_learning_rate: 5.0e-05
  model_type: joint_latent_diffusion_noisy_classifier
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: 0
    image_size: 8
    channels: 4
    monitor: val/accuracy_ema

    sample_grad_scale: 60
    classification_key: 1
    classification_loss_weight: 0.001
    augmentations: True

    classifier_in_features: 4864
    classifier_hidden: 2048
    num_classes: 100
    dropout: 0.0

    unet_config:
      target: models.AdjustedUNet
      params:
        image_size: 8
        in_channels: 4
        out_channels: 4
        model_channels: 256
        attention_resolutions: [ 1, 2, 4 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 3 ]
        num_head_channels: 32
        pool_size: 10000

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
        ckpt_path: "logs/Autoencoder_2023-12-29T17-18-15/checkpoints/epoch=000127.ckpt" #"logs_old/Autoencoder_2023-06-02T13-26-41/checkpoints/epoch=000023.ckpt"
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 32
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 1
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_unconditional__


dataloaders:
  name: cifar100
  train_batches: [ 256 ]
  val_batch: 512
  num_workers: 16
  num_labeled: null


lightning:
  trainer:
    benchmark: True
    checkpoint_callback: True
    max_steps: 1000000
    # accumulate_grad_batches: 2

  callbacks:
    fid_logger:
      batch_frequency: 100000
      samples_amount: 10000
      metrics_batch_size: 1024
      real_dl_batch_size: 256
      latent: True

    img_logger:
      batch_frequency: 10000
      max_images: 10
      clamp: True
      increase_log_steps: False
      log_images_kwargs: {
          "N": 10,
          "inpaint": False,
          "sample_classes": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
      }
