model:
  base_learning_rate: 1.0e-04
  model_type: joint_diffusion_attention_2_optims
  params:
    clip_denoised: True
    beta_schedule: sqrt_linear
    linear_start: 0.001
    linear_end: 0.02
    log_every_t: 200
    timesteps: 1000
    first_stage_key: 0
    image_size: 32
    channels: 3
    monitor: val/loss_ema
    classification_loss_scale: 0.001
    classifier_lr: 1.0e-03
    augmentations: False

    attention_config:
      num_classes: 100
      channels: 64
      dim_head: 16
      context_dims: [128, 128, 128, 128, 128, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256]
      pool_sizes: [8, 8, 8, 8, 4, 4, 4, 4, 2, 2, 2, 2, null, null, null, null, null,]
      mlp_size: 1024
      hidden_size: 1024
      projection_div: 2
      dropout: 0.3

    unet_config:
      target: models.AdjustedUNet
      params:
        image_size: 32
        in_channels: 3
        out_channels: 3
        model_channels: 128
        attention_resolutions: [ 2, 4 ]
        num_res_blocks: 3
        channel_mult: [ 1, 2, 2, 2 ]
        num_heads: 4
        dropout: 0.1
        use_scale_shift_norm: True
        pool_size: 10000


dataloaders:
  validation:  
    name: "cifar10"
    root: "data"
    split: "test"
    download: True
    batch_size: 256
    num_workers: 16
    sampler: "none"
    shuffle: False
    transforms:
      - ToTensor:
      - Permute:
          dims: [1, 2, 0]
      - Normalize:
          mean: [0.5, 0.5, 0.5]
          std: [0.5, 0.5, 0.5]
  train:
    dataset:
      name: "cifar10"
      root: "data"
      split: "train"
      download: True
      batch_size: 256
      num_workers: 16
      sampler: "none"
      shuffle: True
      transforms:
        - ParallelTransforms:
          -
            - ToTensor:
            - Permute:
                dims: [1, 2, 0]
            - Normalize:
                mean: [0.5, 0.5, 0.5]
                std: [0.5, 0.5, 0.5]
          -
            - ToPILImage:
            - RandomHorizontalFlip:
            - RandomCrop:
                size: 32
                padding: 4
                padding_mode: "reflect"
            - RandAugment:
                n: 2
                m: 10
            - ToTensor:
            - Permute:
                dims: [1, 2, 0]
            - Normalize:
                mean: [0.5, 0.5, 0.5]
                std: [0.5, 0.5, 0.5]


lightning:
  trainer:
    benchmark: True
    checkpoint_callback: True
    max_steps: 1000000
    # accumulate_grad_batches: 2

  callbacks:
    fid_logger:
      batch_frequency: 100000
      samples_amount: 10000
      metrics_batch_size: 1024
      real_dl_batch_size: 256
      latent: False

    img_logger:
      batch_frequency: 10000
      max_images: 10
      clamp: True
      increase_log_steps: False
      log_images_kwargs: {
          "N": 40,
          "inpaint": False,
      }
