model:
  base_learning_rate: 4.5e-5
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 8
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 8
      resolution: 32
      in_channels: 3
      out_ch: 3
      ch: 32
      ch_mult: [1,2,2]  # num_down = len(ch_mult)-1
      num_res_blocks: 1
      attn_resolutions: [8]
      dropout: 0.0

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
