model:
  base_learning_rate: 0.0003
  model_type: diffmatch_attention
  params:
    clip_denoised: True
    beta_schedule: sqrt_linear
    linear_start: 0.001
    linear_end: 0.02
    log_every_t: 200
    timesteps: 1000
    first_stage_key: 0
    image_size: 32
    channels: 3
    monitor: val/loss_ema
    classification_loss_weight: 0.001
    batch_size: 32

    attention_config:
      num_classes: 10
      channels: 128
      dim_head: 16
      context_dims: [128, 128, 128, 128, 128, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256]
      pool_sizes: [8, 8, 8, 8, 4, 4, 4, 4, 2, 2, 2, 2, null, null, null, null, null,]
      mlp_size: 2048
      hidden_size: 1024
      projection_div: null
      dropout: 0.3

    unet_config:
      target: models.AdjustedUNet
      params:
        image_size: 32
        in_channels: 3
        out_channels: 3
        model_channels: 128
        attention_resolutions: [ 2, 4 ]
        num_res_blocks: 3
        channel_mult: [ 1, 2, 2, 2 ]
        num_heads: 4
        dropout: 0.1
        use_scale_shift_norm: True
        pool_size: 10000


dataloaders:
  validation:  
    name: "stl10"
    root: "data"
    split: "test"
    download: True
    batch_size: 256
    num_workers: 16
    sampler: "none"
    shuffle: False
    transforms:
      - ToPILImage:
      - Resize:
          size: 32
      - ToTensor:
      - Normalize:
          mean: [0.5, 0.5, 0.5]
          std: [0.5, 0.5, 0.5]
  train:
    - dataset:
        name: "stl10"
        root: "data"
        split: "train"
        download: True
        batch_size: 32
        num_workers: 16
        sampler: "random"
        shuffle: False
        transforms:
          - ToPILImage:
          - Resize:
              size: 32
          - RandomCrop:
              size: 32
              padding: 4
              padding_mode: "reflect"
          - ToTensor:
          - Normalize:
              mean: [0.5, 0.5, 0.5]
              std: [0.5, 0.5, 0.5]

    - dataset:
        name: "stl10"
        root: "data"
        split: "unlabeled"
        download: True
        batch_size: 224
        num_workers: 16
        sampler: "random"
        shuffle: False
        transforms:
          - ParallelTransforms:
            -
              - ToPILImage:
              - Resize:
                  size: 32
              - ToTensor:
              - Normalize:
                  mean: [0.5, 0.5, 0.5]
                  std: [0.5, 0.5, 0.5] 

            - 
              - ToPILImage:
              - Resize:
                  size: 32
              - RandomCrop:
                  size: 32
                  padding: 4
                  padding_mode: "reflect"
              - ToTensor:
              - Normalize:
                  mean: [0.5, 0.5, 0.5]
                  std: [0.5, 0.5, 0.5] 
            
            - 
              - ToPILImage:
              - Resize:
                  size: 32
              - RandomCrop:
                  size: 32
                  padding: 4
                  padding_mode: "reflect"
              - RandAugment:
                  n: 2
                  m: 10
              - ToTensor:
              - Normalize:
                  mean: [0.5, 0.5, 0.5]
                  std: [0.5, 0.5, 0.5]


lightning:
  trainer:
    benchmark: True
    enable_checkpointing: True
    max_steps: 1000000
    accumulate_grad_batches: 2

  callbacks:
    # fid_logger:
    #   batch_frequency: 100000
    #   samples_amount: 10000
    #   metrics_batch_size: 512
    #   real_dl_batch_size: 448
    #   latent: False
    #   mean: [0.5, 0.5, 0.5]
    #   std: [0.5, 0.5, 0.5]

    img_logger:
      batch_frequency: 10000
      max_images: 10
      clamp: True
      increase_log_steps: False
      log_images_kwargs: {
          "N": 40,
          "inpaint": False,
      }
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]