model:
  base_learning_rate: 0.0002
  model_type: joint_diffusion_augmentations
  params:
    clip_denoised: False
    beta_schedule: sqrt_linear
    linear_start: 0.001
    linear_end: 0.02
    log_every_t: 200
    timesteps: 1000
    first_stage_key: 0
    image_size: 32
    channels: 3
    monitor: val/accuracy_ema
    classification_loss_scale: 0.001
    classifier_in_features: 3712
    classifier_hidden: 1024
    num_classes: 10
    dropout: 0.1
    classification_start: 0
    augmentations: False
    sampling_method: "conditional_to_repr"    
    sample_grad_scale: 0

    unet_config:
      target: models.AdjustedUNet
      params:
        image_size: 32
        in_channels: 3
        out_channels: 3
        model_channels: 128
        attention_resolutions: [ 2, 4 ]
        num_res_blocks: 3
        channel_mult: [ 1, 2, 2, 2 ]
        num_heads: 4
        dropout: 0.1
        use_scale_shift_norm: True
        pool_size: 10000

cl:
  grad_scale: 15
  samples_per_class: 5000
  sampling_method: "conditional_to_repr"
  weight_reinit: "unused classes"
  # saved_samples: pulled_checkpoints/cifar10_imgs.pt
  # saved_labels: pulled_checkpoints/cifar10_labels.pt


dataloaders:
  name: cifar10_randaugment
  train_batches: [ 256 ]
  val_batch: 256
  num_workers: 16
  num_labeled: 250
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2471, 0.2435, 0.2616]

lightning:
  trainer:
    benchmark: True
    checkpoint_callback: True
    max_steps: 1000000
    accumulate_grad_batches: 2

  callbacks:
    # fid_logger:
    #   batch_frequency: 100000
    #   samples_amount: 10000
    #   metrics_batch_size: 512
    #   real_dl_batch_size: 448
    #   latent: False
    #   mean: [0.4914, 0.4822, 0.4465]
    #   std: [0.2471, 0.2435, 0.2616]

    img_logger:
      batch_frequency: 10000
      max_images: 40
      clamp: True
      increase_log_steps: False
      log_images_kwargs: {
          "N": 40,
          "inpaint": False,
          "sample_classes": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
          "use_ema": False,
          "grad_scales": [100, 70, 40, 0]
      }
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2471, 0.2435, 0.2616]