model:
  base_learning_rate: 0.0002
  model_type: joint_diffusion_augmentations
  params:
    clip_denoised: True
    beta_schedule: sqrt_linear
    linear_start: 0.001
    linear_end: 0.02
    log_every_t: 200
    timesteps: 1000
    first_stage_key: 0
    image_size: 32
    channels: 3
    monitor: val/accuracy_ema
    classification_loss_scale: 0.001
    classifier_in_features: 3712
    classifier_hidden: 1024
    num_classes: 10
    dropout: 0.1
    classification_start: 0
    augmentations: False
    sampling_method: "conditional_to_x"    
    sample_grad_scale: 0

    unet_config:
      target: models.AdjustedUNet
      params:
        image_size: 32
        in_channels: 3
        out_channels: 3
        model_channels: 128
        attention_resolutions: [ 2, 4 ]
        num_res_blocks: 3
        channel_mult: [ 1, 2, 2, 2 ]
        num_heads: 4
        dropout: 0.1
        use_scale_shift_norm: True
        pool_size: 10000

cl:
  grad_scale: 5
  samples_per_class: 5000
  sampling_method: "conditional_to_repr"
  weight_reinit: "unused classes"
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
  # saved_samples: data/cl/JointDiffusionAugmentations_2024-03-16T16-09-06_imgs.pt
  # saved_labels: data/cl/JointDiffusionAugmentations_2024-03-16T16-09-06_labels.pt


dataloaders:
validation:  
    name: "cifar10"
    root: "data"
    split: "test"
    download: True
    batch_size: 256
    num_workers: 16
    sampler: "none"
    shuffle: False
    transforms:
      - ToTensor:
      - Permute:
          dims: [1, 2, 0]
      - Normalize:
          mean: [0.5, 0.5, 0.5]
          std: [0.5, 0.5, 0.5]
  train:
    - cl_split:
        tasks: [[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]]
        datasets:
          - ssl_split:
              name: "cifar10"
              root: "data"
              split: "train"
              download: True

              num_labeled: 250
              min_labeled: 32
              seed: 42

              supervised:
                batch_size: 32
                num_workers: 16
                sampler: "random"
                shuffle: False
                transforms:
                  - ToPILImage:
                  - RandomHorizontalFlip:
                  - RandomCrop:
                      size: 32
                      padding: 4
                      padding_mode: "reflect"
                  - ToTensor:
                  - Permute:
                      dims: [1, 2, 0]
                  - Normalize:
                      mean: [0.5, 0.5, 0.5]
                      std: [0.5, 0.5, 0.5]

              unsupervised:
                batch_size: 224
                num_workers: 16
                sampler: "random"
                shuffle: False
                transforms:
                  - ParallelTransforms:
                    -
                      - ToTensor:
                      - Normalize:
                          mean: [0.5, 0.5, 0.5]
                          std: [0.5, 0.5, 0.5] 
                      - Permute:
                          dims: [1, 2, 0]

                    - 
                      - ToPILImage:
                      - RandomHorizontalFlip:
                      - RandomCrop:
                          size: 32
                          padding: 4
                          padding_mode: "reflect"
                      - ToTensor:
                      - Permute:
                          dims: [1, 2, 0]
                      - Normalize:
                          mean: [0.5, 0.5, 0.5]
                          std: [0.5, 0.5, 0.5] 
                    
                    - 
                      - ToPILImage:
                      - RandomHorizontalFlip:
                      - RandomCrop:
                          size: 32
                          padding: 4
                          padding_mode: "reflect"
                      - RandAugment:
                          n: 2
                          m: 10
                      - ToTensor:
                      - Permute:
                          dims: [1, 2, 0]
                      - Normalize:
                          mean: [0.5, 0.5, 0.5]
                          std: [0.5, 0.5, 0.5]

lightning:
  trainer:
    benchmark: True
    checkpoint_callback: True
    max_steps: 1000000
    # accumulate_grad_batches: 2

  callbacks:
    # fid_logger:
    #   batch_frequency: 100000
    #   samples_amount: 10000
    #   metrics_batch_size: 512
    #   real_dl_batch_size: 448
    #   latent: False
    #   mean: [0.4914, 0.4822, 0.4465]
    #   std: [0.2471, 0.2435, 0.2616]

    img_logger:
      batch_frequency: 10000
      max_images: 40
      clamp: True
      increase_log_steps: False
      log_images_kwargs: {
          "N": 40,
          "inpaint": False,
          "sample_classes": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
          "use_ema": False,
          "grad_scales": [40, 20, 10, 5, 0]
      }
      # mean: [0.4914, 0.4822, 0.4465]
      # std: [0.2471, 0.2435, 0.2616]
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]