model:
  base_learning_rate: 5.0e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: 0
    image_size: 8
    channels: 4
    monitor: val/loss

    unet_config:
      target: models.AdjustedUNet
      params:
        image_size: 8
        in_channels: 4
        out_channels: 4
        model_channels: 160
        attention_resolutions: [ 1, 2, 4 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 3 ]
        num_head_channels: 32
        pool_size: 4

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
        ckpt_path: "logs/Autoencoder_2023-04-03T13-57-13/checkpoints/epoch=000035.ckpt"
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 32
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 1
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_unconditional__

    classifier_in_features: 4480
    classifier_hidden: 2048
    num_classes: 10
    classification_key: 1

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True