model:
  base_learning_rate: 5.0e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    log_every_t: 200
    timesteps: 1000
    first_stage_key: 0
    image_size: 32
    channels: 3
    monitor: val/loss
    attention_config:
      num_classes: 10
      channels: 64
      dim_head: 32
      context_dims: [480, 480, 480, 320, 320, 320, 160, 160, 160, 160]
      mlp_size: 4096
      hidden_size: 1024
      projection_div: 8

    unet_config:
      target: models.AdjustedUNet
      params:
        image_size: 32
        in_channels: 3
        out_channels: 3
        model_channels: 160
        attention_resolutions: [  ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 3 ]
        num_head_channels: 32
        pool_size: 10000

    # sample_grad_scale: 60
    # classification_key: 1

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True