model:
  base_learning_rate: 0.0002
  model_type: ddpm
  params:
    clip_denoised: True
    beta_schedule: sqrt_linear
    linear_start: 0.001
    linear_end: 0.02
    log_every_t: 200
    timesteps: 100
    first_stage_key: 0
    image_size: 32
    channels: 3
    monitor: val/loss_ema

    # unet_config:
    #   target: models.TwoLayerNet
    #   params:
    #     in_size: 2
    #     hidden_size: 128 
    #     out_size: 2
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 1
        in_channels: 2
        out_channels: 2
        model_channels: 128
        attention_resolutions: [ 1 ]
        num_res_blocks: 2
        channel_mult: [ 1 ]
        num_heads: 4
        dropout: 0.1
        use_scale_shift_norm: True

cl:
  reply_type: "one_supervised_task"
  grad_scale: 0
  # ddim_steps: 250
  samples_per_class: 5000
  sampling_method: "unconditional"
  weight_reinit: "unused classes"
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
  # saved_samples: pulled_checkpoints/samples.pt
  # saved_labels: pulled_checkpoints/labels.pt


dataloaders:
  validation:
      name: "some_points"
      points: [[0.25, 0.25]]
      root: "data"
      split: "test"
      download: True
      batch_size: 256
      num_workers: 16
      sampler: "none"
      shuffle: False
  train:
    - dataset:
        name: "some_points"
        points: [[0.25, 0.25], [0.25, 0.25]]
        download: True
        split: "train"
        batch_size: 128
        num_workers: 16
        sampler: "none"
        shuffle: True



lightning:
  trainer:
    benchmark: True
    enable_checkpointing: True
    max_steps: 120000
    # accumulate_grad_batches: 2

  callbacks:
    # fid_logger:
    #   batch_frequency: 100000
    #   samples_amount: 10000
    #   metrics_batch_size: 512
    #   real_dl_batch_size: 448
    #   latent: False
    #   mean: [0.4914, 0.4822, 0.4465]
    #   std: [0.2471, 0.2435, 0.2616]

    img_logger:
      batch_frequency: 10000000
      max_images: 64
      clamp: True
      increase_log_steps: False
      log_images_kwargs: {
          "N": 64,
          "inpaint": False,
          "sample_classes": [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
          "use_ema": False,
          "grad_scales": [0]
      }
      # mean: [0.4914, 0.4822, 0.4465]
      # std: [0.2471, 0.2435, 0.2616]
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]